fix types breakage in sdk-node due to '| null' unintentionally being allowed in AttributeNameValue#value
This resulted in:
    src/utils.ts:110:7 - error TS2322: Type 'string | number | boolean | string[] | boolean[] | number[] | null' is not assignable to type 'DetectedResourceAttributeValue'.
      Type 'null' is not assignable to type 'DetectedResourceAttributeValue'.
    110       attr[a.name] = a.value;

This improves on the earlier commit a8e1d7c693763c4dde9cd1836d8ede9d7cef3b1d,
which missed this case.