fix(build): ensure 'update-ts-configs' script doesn't blow away 'exclude' entry recently added to configuration/tsconfig.json
We have a postinstall step that updates tsconfig.json files in packages.
I think this is mainly to update the references section, which is
easy to forget to update.

Recently #6650 added an 'exclude' entry to configuration/tsconfig.json.
update-ts-configs.js would just remove that 'exclude' entry during postinstall.
The symptom was that a subsequent 'npm run compile' would error out with

    error TS5055: Cannot write file '.../experimental/packages/configuration/build/src/ConfigFactory.d.ts' because it would overwrite input file.
    ...