Add missing plugins for tracing the sample app
When I followed this guide I got some errors after running 

```sh
$ npm install \
  @opentelemetry/core \
  @opentelemetry/node \
  @opentelemetry/plugin-http
```

The errors:
PluginLoader#load: could not load plugin @opentelemetry/plugin-https of module https. Error: Cannot find module '@opentelemetry/plugin-https'
and
PluginLoader#load: could not load plugin @opentelemetry/plugin-express of module express. Error: Cannot find module '@opentelemetry/plugin-express'

By adding those 2 plugins to the `npm install` I got that step working.